/* ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <info@gerhard-bertelsmann.de> wrote this file. As long as you retain this
 * notice you can do whatever you want with this stuff. If we meet some day,
 * and you think this stuff is worth it, you can buy me a beer in return
 * Gerhard Bertelsmann
 * ----------------------------------------------------------------------------
 */

#ifndef _LOCO_STRINGS_H
#define _LOCO_STRINGS_H

static const char *loco_function_string[] = {
    " ",
    "Stirnbeleuchtung",
    "Innenbeleuchtung",
    "Rücklicht",
    "Fernlicht",
    "Geräusch",
    "Pantograf",
    "Rauch",
    "Rangiergang",
    "Telexkupplung beidseitig",
    "Horn",
    "Schaffnerpfiff",
    "Pfeife",
    "Glocke",
    "Links/Rechts",
    "Heben/Senken",
    "Drehen links",
    "Kranarm heben/senken",
    "ABV",
    "Pumpe",
    "Bremsenquietschen",
    "Schaltstufen",
    "Generator",
    "Betriebsgeräusch",
    "Motor",
    "Bahnhofsansage",
    "Kohle schaufeln",
    "Türen schließen",
    "Türe öffnen",
    "Lüftergeräusch",
    "Lüfter",
    "Feuerbüchse",
    "Innenbeleuchtung",
    "Tischlampe Ep. IV",
    "Tischlampe Ep.III",
    "Tischlampe Ep. II",
    "Schüttelrost",
    "Schienenstoß",
    "Nummernschild",
    "Betriebsgeräusch",
    "Zuglaufschild",
    "Führerstand hinten",
    "Führerstand vorn",
    "Kuppeln",
    "Pufferstoß",
    "Zugansage",
    "Kranhaken",
    "Blinklicht",
    "Führerstandsbel.",
    "Pressluft",
    "F0",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "F25",
    "F26",
    "F27",
    "F28",
    "F29",
    "F30",
    "F31",
    "Telexkupplung hinten",
    "Telexkupplung vorne",
    "Pantograf hinten",
    "Pantograf vorne",
    "Licht hinten",
    "Licht vorne",
    "Heben",
    "Lüfter",
    "Triebwerksbeleuchtung",
    "Zylinder ausblasen",
    "Dampfstoß",
    "Kran",
    "Auf",
    "Ab",
    "Links",
    "Rechts",
    "Drehen rechts",
    "Magnet"
};

#endif /* _LOCO_STRINGS_H */
